# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pick.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.widget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.widget.setStyleSheet("background-color: rgb(0, 95, 55);")
        self.widget.setObjectName("widget")
        self.cancel = QtWidgets.QPushButton(self.widget)
        self.cancel.setGeometry(QtCore.QRect(30, 30, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("QPushButton{\n"
"font: 30pt \"Wingdings\";\n"
"background-color: rgb(0, 95, 55);\n"
"color: rgb(0, 170, 0);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton::pressed{\n"
"background-color: rgb(0, 95, 55);\n"
"color:rgb(115, 230, 0);\n"
"}")
        self.cancel.setObjectName("cancel")
        self.coffee = QtWidgets.QPushButton(self.widget)
        self.coffee.setGeometry(QtCore.QRect(150, 100, 287, 450))
        font = QtGui.QFont()
        font.setKerning(True)
        self.coffee.setFont(font)
        self.coffee.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.coffee.setToolTipDuration(-4)
        self.coffee.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 95, 55);\n"
"border-radius: 30px;\n"
"}")
        self.coffee.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Images/coffee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.coffee.setIcon(icon)
        self.coffee.setIconSize(QtCore.QSize(287, 450))
        self.coffee.setObjectName("coffee")
        self.tea = QtWidgets.QPushButton(self.widget)
        self.tea.setGeometry(QtCore.QRect(587, 100, 287, 450))
        self.tea.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"border-radius: 30px;\n"
"")
        self.tea.setText("")
        self.tea.setObjectName("tea")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cancel.setText(_translate("MainWindow", "Û"))
# import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
