# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomescreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        # Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        # Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background-color:rgb(255, 217, 0)")
        self.widget.setObjectName("widget")

        self.welcome = QtWidgets.QLabel(self.widget)
        self.welcome.setGeometry(QtCore.QRect(130, 180, 371, 61))
        self.welcome.setStyleSheet("font: 87 40pt \"Arial Black\"; background-color: rgb(255, 217, 0);color:rgb(255, 255, 255)")
        self.welcome.setObjectName("welcome")

        self.start = QtWidgets.QPushButton(self.widget)
        self.start.setGeometry(QtCore.QRect(240, 330, 171, 51))
        self.start.setStyleSheet("background-color: rgb(240, 0, 104);\n"
"border-radius: 10px;\n"
"font: 87 18pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.start.setObjectName("start")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.welcome.setText(_translate("Dialog", "WELCOME"))
        self.start.setText(_translate("Dialog", "START"))
